### ISSUE TITLE
Prod: EtherScan link is Undefined after completion of withdraw Tx

### ISSUE THREAD

**Issue by yuneeksehgal** [loomnetwork/dashboard#425]
![image](https://user-images.githubusercontent.com/23660413/56041015-5c151680-5d55-11e9-870b-c7cb310b268e.png)

**Comment by redben** [comment]
@yuneeksehgal can you confirm this is fixed?

**Comment by yuneeksehgal** [comment]
@redben This one still exists on prod

![image](https://user-images.githubusercontent.com/23660413/56503678-d0a93b80-6533-11e9-8a0b-f46f31904bd0.png)

**Comment by yuneeksehgal** [comment]
Still Exists on US1

**Comment by yuneeksehgal** [comment]
This is fixed now.
